### ISSUE TITLE
Error when patch and source files are almost empty

### ISSUE THREAD

**Issue by kototama** [larsyencken/csvdiff#29]
Hello,

First, thank you for writing this tool. Very useful.

I got this error:
```
Traceback (most recent call last):
  File "/home/user/.local/bin/csvpatch", line 11, in <module>
    sys.exit(csvpatch_cmd())
  File "/home/user/.local/lib/python3.4/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.local/lib/python3.4/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/user/.local/lib/python3.4/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.local/lib/python3.4/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/user/.local/lib/python3.4/site-packages/csvdiff/__init__.py", line 218, in csvpatch_cmd
    patch_file(patch_stream, fromcsv_stream, tocsv_stream, strict=strict)
  File "/home/user/.local/lib/python3.4/site-packages/csvdiff/__init__.py", line 69, in patch_file
    fieldnames = from_records.fieldnames
AttributeError: 'generator' object has no attribute 'fieldnames'

```

when applying an empty patch file

```
{
  "_index": [
    "W",
    "B",
    "B2"
  ],
  "added": [],
  "changed": [],
  "removed": []
}
``` 

to an almost empty document:
```
"UE","W","B","B2","B3","UB",
```

**Comment by larsyencken** [comment]
Thanks for the report. I found the problem and put out a new release: https://pypi.python.org/pypi/csvdiff/0.3.2

**Comment by kototama** [comment]
Thank you very much.
