### ISSUE TITLE
test failed

### ISSUE THREAD

**Issue by williamjmorenor** [larsyencken/csvdiff#3]
Hi

I am trying to setup a .spec file for include csvdiff in Fedora but I have a got this error with test

running build_ext
Traceback (most recent call last):
  File "setup.py", line 54, in <module>
    test_suite='tests',
  File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/test.py", line 138, in run
    self.with_project_on_sys_path(self.run_tests)
  File "/usr/lib/python2.7/site-packages/setuptools/command/test.py", line 118, in with_project_on_sys_path
    func()
  File "/usr/lib/python2.7/site-packages/setuptools/command/test.py", line 164, in run_tests
    testLoader = cks
  File "/usr/lib64/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib64/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib64/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib64/python2.7/unittest/loader.py", line 128, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib64/python2.7/unittest/loader.py", line 103, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/usr/lib/python2.7/site-packages/setuptools/command/test.py", line 35, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib64/python2.7/unittest/loader.py", line 100, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'test_core'
error: Estado de salida erróneo de /var/tmp/rpm-tmp.LrMw5o (%check)

**Comment by larsyencken** [comment]
I just put out a new release (v0.3.0) that doesn't depend on PyYAML, instead it uses click and jsonschema. Want to try again with that?

It also adds a matching `csvpatch` command with its own man page.

**Comment by williamjmorenor** [comment]
Cool

I will update the package, now it is in the package repo of Fedora 21 and (than will be) Fedora 22

https://admin.fedoraproject.org/pkgdb/package/csvdiff/

**Comment by larsyencken** [comment]
Thanks William!
