### ISSUE TITLE
Tests fail (5 failures, 3 errors) on Windows 10 with Python 2.7.14

### ISSUE THREAD

**Issue by friederschueler** [larsyencken/csvdiff#35]
```$ python setup.py test
running test
running egg_info
writing requirements to csvdiff.egg-info\requires.txt
writing csvdiff.egg-info\PKG-INFO
writing top-level names to csvdiff.egg-info\top_level.txt
writing dependency_links to csvdiff.egg-info\dependency_links.txt
writing entry points to csvdiff.egg-info\entry_points.txt
reading manifest file 'csvdiff.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'csvdiff.egg-info\SOURCES.txt'
running build_ext
test_csvdiff_fails_without_enough_arguments (tests.test_csvdiff.TestCsvdiff) ... ok
test_csvdiff_fails_without_valid_key (tests.test_csvdiff.TestCsvdiff) ... ok
test_diff_command_valid_usage_with_difference (tests.test_csvdiff.TestCsvdiff) ... FAIL
test_diff_command_valid_usage_with_separator (tests.test_csvdiff.TestCsvdiff) ... FAIL
test_diff_records_multikey (tests.test_csvdiff.TestCsvdiff) ... ok
test_diff_records_nonstr_values (tests.test_csvdiff.TestCsvdiff) ... ok
test_diff_records_str_values (tests.test_csvdiff.TestCsvdiff) ... ok
test_diff_with_index_as_ignore_field (tests.test_csvdiff.TestCsvdiff) ... ERROR
test_diff_with_valid_ignore (tests.test_csvdiff.TestCsvdiff) ... ERROR
test_patch_add (tests.test_csvdiff.TestCsvdiff) ... ok
test_patch_change (tests.test_csvdiff.TestCsvdiff) ... ok
test_patch_cmd_fails_when_json_doesnt_match_schema (tests.test_csvdiff.TestCsvdiff) ... FAIL
test_patch_cmd_fails_when_json_is_invalid (tests.test_csvdiff.TestCsvdiff) ... FAIL
test_patch_cmd_valid_args (tests.test_csvdiff.TestCsvdiff) ... FAIL
test_patch_remove (tests.test_csvdiff.TestCsvdiff) ... ok
test_patch_schema_is_valid (tests.test_csvdiff.TestCsvdiff) ... ok
test_summarize (tests.test_csvdiff.TestCsvdiff) ... ok
test_summarize_cmd (tests.test_csvdiff.TestCsvdiff) ... ERROR
test_summarize_identical (tests.test_csvdiff.TestCsvdiff) ... ok

======================================================================
ERROR: test_diff_with_index_as_ignore_field (tests.test_csvdiff.TestCsvdiff)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\workspace\csvdiff\tests\test_csvdiff.py", line 321, in test_diff_with_index_as_ignore_field
    result = self.csvdiff_summary_cmd('id', self.a_file, self.b_file, ignore_columns='id')
  File "c:\workspace\csvdiff\tests\test_csvdiff.py", line 67, in csvdiff_summary_cmd
    with open(t.name, 'r') as istream:
IOError: [Errno 13] Permission denied: 'c:\\users\\fsc\\appdata\\local\\temp\\tmp9f2e3k'

======================================================================
ERROR: test_diff_with_valid_ignore (tests.test_csvdiff.TestCsvdiff)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\workspace\csvdiff\tests\test_csvdiff.py", line 312, in test_diff_with_valid_ignore
    with tmp_csv_files(lhs, rhs) as (lhs_file, rhs_file):
  File "C:\Python27\lib\contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "c:\workspace\csvdiff\tests\test_csvdiff.py", line 413, in tmp_csv_files
    save_as_csv(arg, t.name)
  File "c:\workspace\csvdiff\tests\test_csvdiff.py", line 420, in save_as_csv
    with open(filename, 'w') as ostream:
IOError: [Errno 13] Permission denied: 'c:\\users\\fsc\\appdata\\local\\temp\\tmpu841l8'

======================================================================
ERROR: test_summarize_cmd (tests.test_csvdiff.TestCsvdiff)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\workspace\csvdiff\tests\test_csvdiff.py", line 118, in test_summarize_cmd
    with tmp_csv_files(lhs, rhs) as (lhs_file, rhs_file):
  File "C:\Python27\lib\contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "c:\workspace\csvdiff\tests\test_csvdiff.py", line 413, in tmp_csv_files
    save_as_csv(arg, t.name)
  File "c:\workspace\csvdiff\tests\test_csvdiff.py", line 420, in save_as_csv
    with open(filename, 'w') as ostream:
IOError: [Errno 13] Permission denied: 'c:\\users\\fsc\\appdata\\local\\temp\\tmprp8oqu'

======================================================================
FAIL: test_diff_command_valid_usage_with_difference (tests.test_csvdiff.TestCsvdiff)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\workspace\csvdiff\tests\test_csvdiff.py", line 157, in test_diff_command_valid_usage_with_difference
    self.assertEqual(result.exit_code, 1)
AssertionError: -1 != 1

======================================================================
FAIL: test_diff_command_valid_usage_with_separator (tests.test_csvdiff.TestCsvdiff)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\workspace\csvdiff\tests\test_csvdiff.py", line 179, in test_diff_command_valid_usage_with_separator
    self.assertEqual(result.exit_code, 1)
AssertionError: -1 != 1

======================================================================
FAIL: test_patch_cmd_fails_when_json_doesnt_match_schema (tests.test_csvdiff.TestCsvdiff)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\workspace\csvdiff\tests\test_csvdiff.py", line 343, in test_patch_cmd_fails_when_json_doesnt_match_schema
    self.assertEqual(result.exit_code, 2)
AssertionError: -1 != 2

======================================================================
FAIL: test_patch_cmd_fails_when_json_is_invalid (tests.test_csvdiff.TestCsvdiff)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\workspace\csvdiff\tests\test_csvdiff.py", line 338, in test_patch_cmd_fails_when_json_is_invalid
    self.assertEqual(result.exit_code, 2)
AssertionError: -1 != 2

======================================================================
FAIL: test_patch_cmd_valid_args (tests.test_csvdiff.TestCsvdiff)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\workspace\csvdiff\tests\test_csvdiff.py", line 329, in test_patch_cmd_valid_args
    self.assertEqual(result.exit_code, 0)
AssertionError: -1 != 0

----------------------------------------------------------------------
Ran 19 tests in 0.030s

FAILED (failures=5, errors=3)
```

Windows 10, Version 1709
Python 2.4.17

**Comment by larsyencken** [comment]
Thanks for the report. Unfortunately I don't have the capacity to easily test on windows, so I can't support it for now.
