### ISSUE TITLE
diff = csvdiff.diff_files('output.txt', 'input.txt',[])

### ISSUE THREAD

**Issue by karakutu001** [larsyencken/csvdiff#39]
I am trying to run in basic form this module. 

```
import csvdiff


diff = csvdiff.diff_files('output.txt', 'input.txt',[])


print(diff)
```

I am a littel bit confused. i am getting following errors:

"/python/test.py"
Traceback (most recent call last):
  File "XXXX/python/test.py", line 4, in <module>
    diff = csvdiff.diff_files('output.txt', 'input.txt',[])
  File "C:\Users\DDDDD\AppData\Roaming\Python\Python37\site-packages\csvdiff\__init__.py", line 44, in diff_files
    ignore_columns=ignored_columns)
  File "C:\Users\DDDDD\AppData\Roaming\Python\Python37\site-packages\csvdiff\patch.py", line 211, in create
    return create_indexed(from_indexed, to_indexed, index_columns)
  File "C:\Users\DDDDD\AppData\Roaming\Python\Python37\site-packages\csvdiff\patch.py", line 222, in create_indexed
    index_columns)
  File "C:\Users\DDDDD\AppData\Roaming\Python\Python37\site-packages\csvdiff\patch.py", line 252, in _assemble
    key=_change_key)
  File "C:\Users\DDDDD\AppData\Roaming\Python\Python37\site-packages\csvdiff\patch.py", line 251, in <genexpr>
    for k in changed),
  File "C:\Users\DDDDD\AppData\Roaming\Python\Python37\site-packages\csvdiff\patch.py", line 264, in record_diff
    from_ = lhs[k]
KeyError: 'CAFEE01'

Process finished with exit code 1
```

**Comment by larsyencken** [comment]
Hey. So the diff requires one or more index columns to act as primary keys. That way you can identify records which are the same, but have been modified. Try again with index columns.
