### ISSUE TITLE
Syntax error line 53 for python 2.6.6

### ISSUE THREAD

**Issue by Xaraxia** [larsyencken/csvdiff#52]
Just an FYI - it installs through PIP, so I expected it to work. If you're not supporting old versions that's fair.

Traceback (most recent call last):
  File "/usr/bin/csvdiff", line 7, in <module>
    from csvdiff import csvdiff_cmd
  File "/usr/lib/python2.6/site-packages/csvdiff/__init__.py", line 14, in <module>
    from . import records, patch, error
  File "/usr/lib/python2.6/site-packages/csvdiff/records.py", line 53
    for r in record_seq
      ^
SyntaxError: invalid syntax

**Comment by simbo1905** [comment]
Can you please post a small example that demonstrates the problem including the two files and the commandline? 

For example here is an example of testing out two small files that shows no bugs: 

```
± |master ?:27 ✗| → head a.csv b.csv 
==> a.csv <==
id,name,amount
1,bob,20
2,eva,63
3,sarah,7
4,jeff,19
6,fred,10

==> b.csv <==
id,name,amount
1,bob,20
2,eva,63
3,sarah,7
4,jeff,19
6,fred,10

 2019-05-22 05:49:29 ⌚  |2.4.4| MacBook-Pro-3 in ~/projects/csvdiff
± |master ?:27 ✗| → csvdiff --style=summary id a.csv b.csv 
files are identical
```
